/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        inter: ["'Inter'", '-apple-system', 'BlinkMacSystemFont', "'Segoe UI'", 'sans-serif'],
      },
      colors: {
        navy: '#00338D',
        blue: '#0091DA',
        violet: '#483698',
        amber: '#E08A00',
        red: '#D8443C',
        green: '#1B7A5A',
        ink: '#15202B',
        grey: '#5A6B7B',
        paper: '#F7FAFD',
        line: '#D7E3EF',
        'navy-5': 'rgba(0, 51, 141, 0.05)',
        'navy-10': 'rgba(0, 51, 141, 0.10)',
        'blue-10': 'rgba(0, 145, 218, 0.10)',
        'violet-10': 'rgba(72, 54, 152, 0.10)',
        'green-10': 'rgba(27, 122, 90, 0.10)',
        'amber-10': 'rgba(224, 138, 0, 0.10)',
        'sky-gradient-top': '#eaf5fc',
        'sky-gradient-bottom': '#cfe8f7',
        'snow-white': '#ffffff',
        'snow-blue': '#dbe9f2',
        'terrace-1': '#7BAE5B',
        'terrace-2': '#6BA24C',
        'terrace-3': '#5C963F',
        'terrace-4': '#4F8836',
        'terrace-soil': '#caa86f',
        'silver': '#E2E8F0',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        card: "0 4px 20px rgba(0, 51, 141, 0.06)",
        "card-hover": "0 8px 30px rgba(0, 51, 141, 0.10)",
        "card-lg": "0 12px 40px rgba(0, 51, 141, 0.12)",
        cta: "0 4px 16px rgba(0, 145, 218, 0.35)",
        "dashboard": "0 8px 40px rgba(0, 51, 141, 0.10)",
        "dropdown": "0 12px 48px rgba(0, 51, 141, 0.14)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "pulse-dot": {
          "0%": { opacity: "1", r: "3" },
          "50%": { opacity: "0.3", r: "4" },
          "100%": { opacity: "1", r: "3" },
        },
        "ping": {
          "0%": { r: "3", opacity: "0.9" },
          "70%": { r: "26", opacity: "0" },
          "100%": { opacity: "0" },
        },
        "dash": {
          to: { strokeDashoffset: "-28" },
        },
        "alert": {
          "0%, 100%": { opacity: "0.55" },
          "50%": { opacity: "1" },
        },
        "marquee": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(-100%)" },
        },
        "fly": {
          "0%": { transform: "translate(40px, 300px)" },
          "18%": { transform: "translate(300px, 250px)" },
          "38%": { transform: "translate(560px, 300px)" },
          "58%": { transform: "translate(820px, 265px)" },
          "78%": { transform: "translate(560px, 300px)" },
          "100%": { transform: "translate(40px, 300px)" },
        },
        "reveal": {
          "0%": { opacity: "0" },
          "12%": { opacity: "0" },
          "20%": { opacity: "0.55" },
          "88%": { opacity: "0.55" },
          "100%": { opacity: "0" },
        },
        "orbit": {
          "0%": { transform: "translateX(0)" },
          "50%": { transform: "translateX(34px)" },
          "100%": { transform: "translateX(0)" },
        },
        "bounce-chevron": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(8px)" },
        },
        "scan-line": {
          "0%": { top: "0%" },
          "100%": { top: "100%" },
        },
        "gradient-shift": {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        "drop": {
          "0%": { opacity: "0", transform: "translateY(0)" },
          "20%": { opacity: "0.9" },
          "100%": { opacity: "0", transform: "translateY(46px)" },
        },
        "blip": {
          "0%, 100%": { opacity: "0.2" },
          "50%": { opacity: "1" },
        },
        "spin-rotor": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "scroll-reveal": {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "pulse-dot": "pulse-dot 2s ease-in-out infinite",
        "ping": "ping 3.4s ease-out infinite",
        "dash": "dash 1.1s linear infinite",
        "alert": "alert 2.6s ease-in-out infinite",
        "marquee": "marquee 20s linear infinite",
        "fly": "fly 13s ease-in-out infinite",
        "reveal": "reveal 13s linear infinite",
        "orbit": "orbit 9s ease-in-out infinite",
        "bounce-chevron": "bounce-chevron 1.5s infinite",
        "scan-line": "scan-line 8s linear infinite",
        "gradient-shift": "gradient-shift 10s ease infinite",
        "drop": "drop 1.6s ease-in infinite",
        "blip": "blip 2.2s ease-in-out infinite",
        "spin-rotor": "spin-rotor 0.12s linear infinite",
        "scroll-reveal": "scroll-reveal 0.6s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
